seed_everything: 42
trainer:
  deterministic: true
  enable_checkpointing: true
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  precision: bf16-mixed
  max_epochs: 500
  val_check_interval: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: 0
  # accumulate_grad_batches: 4
  # gradient_clip_val: 1.0

callbacks:
  lr_monitor:
    logging_interval: step
  image_logger:
    batch_frequency: 3000
    max_images: 4
    increase_log_steps: false
  ckpt_callback:
    save_top_k: 1
    monitor: "val_loss"
    mode: min
    filename: '{epoch}-{step}-{val_loss:.4f}'

wandb:
  name: "TextArtT5 bf16-mixed perturb_prob 0.0"
  project: "TextArt"
  mode: "offline"

model:
  image_tokenizer_path_or_id: vqgan_tokenizer
  train_config:
    perturb_prob: 0.0
    learning_rate: 1.0e-04
    interval: step
    cosine_scheduler:
      t_in_epochs: false
      t_initial: 75000
      lr_min: 1.0e-06

      cycle_mul: 1.0
      cycle_limit: 2
      cycle_decay: 0.6

      warmup_t: 500
      warmup_lr_init: 0.000001
      warmup_prefix: true

data:
  image_size: [ 256, 256 ]
  data_path: /path/to/CelebA-Dialog
  img_type: png
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 24
  aug: true
